### PR TITLE
Update unit tests

### PR DESCRIPTION
**Pull request by artokin**

### CODE REVIEW

**Comment by artokin** [comment]
rebuild

**Comment by artokin** [comment]
test this please

**Comment by artokin** [comment]
rebuild

**Comment by artokin** [comment]
rebuild

**Comment by artokin** [comment]
rebuild

**Comment by artokin** [comment]
test this please

**Comment by artokin** [comment]
@mikter @AnttiKauppila would you pelase review?

**Comment by mikter** [comment]
ok

**Pull request merged**
